version: "3.4"

volumes:
  db-data:
  media:

services:
  api:
    image: cesium
    build:
      dockerfile: ./docker/Dockerfile
      target: django
      context: .
    depends_on:
      - db
      - redis
      - es
    extra_hosts:
      - cesium.tv:192.168.1.239
    volumes:
      - ./docker/entrypoint-django.sh:/entrypoint.sh:ro
      - ./api:/app
      - media:/media
    environment:
      - DJANGO_DEBUG=true
      - DJANGO_DB_USER=user
      - DJANGO_DB_PASSWORD=password
      - DJANGO_SU_USERNAME=btimby
      - DJANGO_SU_EMAIL=btimby_indy@yahoo.com
      - DJANGO_SU_PASSWORD=password
      - DJANGO_ALLOWED_HOSTS=api
      - AUTHLIB_INSECURE_TRANSPORT=true
      - DJANGO_ES_INSECURE_TRANSPORT=true
      - DJANGO_ES_HOST=es
      - DJANGO_ES_PORT=9200
    env_file:
      # See .env.template for instructions.
      - .env

  ui:
    image: vue
    build:
      dockerfile: ./docker/Dockerfile
      context: .
      target: vue
    depends_on:
      - api
    ports:
      - 8000:8000
    volumes:
      - ./docker/entrypoint-vue.sh:/entrypoint.sh:ro
      - ./ui:/app:ro

  beat:
    image: cesium
    command: beat
    depends_on:
      - db
      - redis
    volumes:
      - ./docker/entrypoint-django.sh:/entrypoint.sh:ro
      - ./api:/app:ro
    environment:
      - DJANGO_DB_USER=user
      - DJANGO_DB_PASSWORD=password
      - DJANGO_ES_INSECURE_TRANSPORT=true
      - DJANGO_ES_HOST=es
      - DJANGO_ES_PORT=9200
    env_file:
      # See .env.template for instructions.
      - .env

  celery:
    image: cesium
    command: celery
    depends_on:
      - db
      - redis
      - es
    extra_hosts:
      - cesium.tv:192.168.1.239
    volumes:
      - ./docker/entrypoint-django.sh:/entrypoint.sh:ro
      - ./api:/app:ro
    environment:
      - DJANGO_DB_USER=user
      - DJANGO_DB_PASSWORD=password
      - DJANGO_ES_INSECURE_TRANSPORT=true
      - DJANGO_ES_HOST=es
      - DJANGO_ES_PORT=9200
    env_file:
      # See .env.template for instructions.
      - .env

  flower:
    image: mher/flower
    environment:
      - FLOWER_PORT=8888
      - CELERY_BROKER_URL=redis://redis:6379/0
    ports:
      - "8888:8888"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3-amd64
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.transport.ssl.enabled=false

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cesium
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
