# Generated by Django 4.0.7 on 2022-08-29 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='favicon',
            field=models.ImageField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico'])]),
        ),
    ]
