# Generated by Django 4.0.7 on 2022-10-06 05:25

from django.db import migrations
import rest.models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_alter_brand_colors_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=rest.models.ImageField(blank=True, null=True, upload_to=rest.models.get_file_name),
        ),
    ]
